### ISSUE TITLE
Question: can this be used to capture pictures from integrated cameras?

### ISSUE THREAD

**Issue by sekulicb** [victor-david/camera-eye#11]
Hi, thanks for this amazing library.

I was wondering can this library be used in order to capture snapshot from integrated cameras in laptops and tablets?

Thanks

**Comment by victor-david** [comment]
I don't think so. The app connects to an IP address that's serving video either via http or rtsp. I don't _think_ that's the way an integrated camera works. But then again, I've never looked into it.

**Comment by sekulicb** [comment]
Thanks.

You are right, it's just not the way to go with development.

Yes, but the problem remains the same...what serves the mini-server with the camera feed. You get my point.

Closing.
