### ISSUE TITLE
How do I choice a RTSP or MJPEG  protocols as a plugin of your Cam-Eye project?

### ISSUE THREAD

**Issue by guytechNet** [victor-david/camera-eye#14]
Hi author,

How do I choice a RTSP or MJPEG  protocols as a plugin of your project?

Can you demo this app for choice a RTSP or MJPEG  protocols as a plugin of your project?

**Comment by victor-david** [comment]
You don't choose RTSP or MPEG directly. You choose it by which plugin you select. It's the plugin that supports RTSP or MPEG or (possibly) both. The three plugins that are part of this project are:
1. Amcrest - supports RTSP and MPEG streams. You can see [its constructor](https://github.com/victor-david/camera-eye/blob/master/src/Restless.Plugin.Amcrest/AmcrestCgiController.cs).
2. Axis - Supports MPEG only. See its [constructor](https://github.com/victor-david/camera-eye/blob/master/src/Restless.Plugin.Axis/AxisBasicController.cs) also.
3. Foscam - MPEG only. See [its constructor](https://github.com/victor-david/camera-eye/blob/master/src/Restless.Plugin.Foscam/FoscamSdController.cs).

Plugins also define the path to the video stream, and (if implemented) commands for moving, setting presets, etc. It depends on which interface(s) they implement. For instance, Amcrest uses the following paths to video.

~~~c#
private const string RtspVideoStreamPath0 = "cam/realmonitor?channel=1&subtype=0";
private const string RtspVideoStreamPath1 = "cam/realmonitor?channel=1&subtype=1";
private const string MjpegVideoStreamPath = "cgi-bin/mjpg/video.cgi?channel=1&subtype=1";
~~~

If none of these plugins are appropriate for your camera, you can create another plugin that is. You can derive from classes in Restless.Plugin.Framework if you want, but it's not mandatory. This is mentioned in the readme.

**Comment by guytechNet** [comment]
Hi author,

We used **Hanwha** Devices which it has the List below is the proper formatting for **Hanwha** devices:
IP Cameras:
rtsp://<DeviceIP>/profile<no>/media.smp
rtsp://<DeviceIP>:port/profile<no>/media.smp
rtsp://user:password@<DeviceIP>:port/profile<no>/media.smp

For example:  rtsp://192.168.1.210:554/profile1/media.smp 
It will stream main stream from Camera with ip: 192.168.1.210

**So, can you help me use it with your project?**

**Comment by victor-david** [comment]
No, I can't help you. That would require a plugin for that particular camera. That would be up to you if you'd like to create one. I cannot create a plugin for a camera type that I don't have because I would have no way to test that it works right.
